# Generated by Django 2.0 on 2018-07-10 08:45

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases_con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='案例标题')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='关键词')),
                ('thumbnail', models.ImageField(blank=True, default='215bg.png', upload_to='cases/%Y/%m/', verbose_name='缩略图')),
                ('uptime', models.DateField(verbose_name='项目上线时间')),
                ('hangye', models.CharField(max_length=50, verbose_name='所属行业')),
                ('corporate_nane', models.CharField(max_length=50, verbose_name='公司名称')),
                ('url', models.URLField(help_text='网址需要输入http://或https://', verbose_name='公司网址')),
                ('pro_one', models.CharField(max_length=20, verbose_name='主推产品1')),
                ('pro_one_url', models.URLField(help_text='网址需要输入http://或https://', verbose_name='主推产品1链接')),
                ('pro_two', models.CharField(max_length=20, verbose_name='主推产品2')),
                ('pro_two_url', models.URLField(help_text='网址需要输入http://或https://', verbose_name='主推产品1链接')),
                ('pro_three', models.CharField(max_length=20, verbose_name='主推产品3')),
                ('pro_three_url', models.URLField(help_text='网址需要输入http://或https://', verbose_name='主推产品3链接')),
                ('pro_four', models.CharField(blank=True, max_length=20, verbose_name='主推产品4')),
                ('pro_four_url', models.URLField(blank=True, help_text='网址需要输入http://或https://', verbose_name='主推产品4链接')),
                ('pro_five', models.CharField(blank=True, max_length=20, verbose_name='主推产品5')),
                ('pro_five_url', models.URLField(blank=True, help_text='网址需要输入http://或https://', verbose_name='主推产品5链接')),
                ('excerpt', models.TextField(max_length=200, verbose_name='公司介绍')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='项目展示')),
                ('data', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='数据展示')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='文章点击率')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('auditing', models.CharField(choices=[('未审核', '未审核'), ('未通过', '未通过'), ('已审核', '已审核')], default='未审核', max_length=10, verbose_name='文章状态')),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顾问')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category_pro', verbose_name='顶级分类')),
                ('category_grandson', models.ForeignKey(blank=True, help_text='请认真选择栏目', on_delete=django.db.models.deletion.CASCADE, to='product.Category_pro_grandson', verbose_name='三级分类')),
                ('category_son', models.ForeignKey(help_text='请认真选择栏目', on_delete=django.db.models.deletion.CASCADE, to='product.Category_pro_son', verbose_name='二级分类')),
                ('pro', models.ManyToManyField(blank=True, to='product.Pro_content', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '案例详细',
                'verbose_name_plural': '案例详细',
            },
        ),
    ]
