# Generated by Django 2.0 on 2018-07-10 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='广告名')),
                ('url', models.URLField(verbose_name='广告地址')),
                ('thumbnail', models.ImageField(blank=True, help_text='轮播图尺寸：980 * 518', upload_to='ad/%Y/%m/', verbose_name='广告图')),
                ('index', models.IntegerField(default=999, verbose_name='广告排序')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
            },
        ),
        migrations.CreateModel(
            name='Index_banner_ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='广告名')),
                ('url', models.URLField(verbose_name='广告地址')),
                ('thumbnail', models.ImageField(blank=True, help_text='宽度1190，高度不限', upload_to='ad_news/%Y/%m/', verbose_name='广告图')),
                ('index', models.IntegerField(default=999, help_text='数值越大越靠后', verbose_name='广告排序')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '首页广告',
                'verbose_name_plural': '首页广告',
            },
        ),
        migrations.CreateModel(
            name='Index_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='广告名')),
                ('url', models.URLField(verbose_name='广告地址')),
                ('thumbnail', models.ImageField(blank=True, help_text='图片尺寸：980 * 518', upload_to='ad_news/%Y/%m/', verbose_name='广告图')),
                ('index', models.IntegerField(default=999, help_text='数值越大越靠后', verbose_name='广告排序')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '底部轮播',
                'verbose_name_plural': '底部轮播',
            },
        ),
        migrations.CreateModel(
            name='Main_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='广告名')),
                ('url', models.URLField(verbose_name='广告地址')),
                ('thumbnail', models.ImageField(blank=True, help_text='图片宽度：1190px，高度不限', upload_to='ad_news/%Y/%m/', verbose_name='广告图')),
                ('index', models.IntegerField(default=999, help_text='数值越大越靠后', verbose_name='广告排序')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ManyToManyField(to='product.Category_pro', verbose_name='一级分类')),
                ('category_grandson', models.ManyToManyField(blank=True, to='product.Category_pro_grandson', verbose_name='三级分类')),
                ('category_son', models.ManyToManyField(blank=True, to='product.Category_pro_son', verbose_name='二级分类')),
            ],
            options={
                'verbose_name': '产品列表',
                'verbose_name_plural': '产品列表',
            },
        ),
        migrations.CreateModel(
            name='Menu_nav_ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('左侧大图', '左侧大图'), ('右侧小图', '右侧小图')], max_length=10, verbose_name='图片类型')),
                ('name', models.CharField(max_length=100, verbose_name='广告名')),
                ('url', models.URLField(verbose_name='广告地址')),
                ('thumbnail', models.ImageField(blank=True, help_text='小图尺寸：宽250px、大图尺寸：宽657px，高度不限', upload_to='ad_news/%Y/%m/', verbose_name='广告图')),
                ('index', models.IntegerField(default=999, help_text='数值越大越靠后', verbose_name='广告排序')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category_pro', verbose_name='一级分类')),
            ],
            options={
                'verbose_name': '导航广告',
                'verbose_name_plural': '导航广告',
            },
        ),
    ]
