# Generated by Django 2.0 on 2018-07-10 08:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_news_tit', models.CharField(max_length=20, verbose_name='栏目名称')),
                ('Category_news_seo', models.CharField(max_length=100, verbose_name='SEO标题')),
                ('Category_news_key', models.CharField(max_length=200, verbose_name='关键词')),
                ('Category_news_des', models.TextField(max_length=200, verbose_name='栏目描述')),
                ('index', models.IntegerField(default=999, verbose_name='分类的排序')),
            ],
            options={
                'verbose_name': '新闻栏目',
                'verbose_name_plural': '新闻栏目',
            },
        ),
        migrations.CreateModel(
            name='News_con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='关键词')),
                ('excerpt', models.TextField(blank=True, help_text='如未填写,则在内容中取60个字作为简介', max_length=200, verbose_name='摘要')),
                ('thumbnail', models.ImageField(blank=True, default='215bg.png', upload_to='news/%Y/%m/', verbose_name='缩略图')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('count', models.PositiveIntegerField(default=1, verbose_name='文章点击率')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category_news', verbose_name='新闻分类')),
            ],
            options={
                'verbose_name': '新闻详细',
                'verbose_name_plural': '新闻详细',
            },
        ),
    ]
