# Generated by Django 2.0 on 2018-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=100, verbose_name='名称对应的id')),
                ('type', models.CharField(max_length=100, verbose_name='类型')),
                ('adviser_con', models.IntegerField(blank=True, null=True, verbose_name='顾问询单量')),
                ('adviser_order', models.IntegerField(blank=True, null=True, verbose_name='顾问下单量')),
                ('cases_count', models.IntegerField(blank=True, null=True, verbose_name='案例访问量')),
                ('news_count', models.IntegerField(blank=True, null=True, verbose_name='案例访问量')),
                ('product_count', models.IntegerField(blank=True, null=True, verbose_name='产品下单量')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
