# Generated by Django 2.0 on 2018-07-10 08:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='专题标题')),
                ('seo_title', models.CharField(max_length=100, verbose_name='SEO标题')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='关键词')),
                ('excerpt', models.TextField(blank=True, help_text='如未填写,则在内容中取60个字作为简介', max_length=200, verbose_name='摘要')),
                ('thumbnail', models.ImageField(blank=True, default='215bg.png', upload_to='topic/%Y/%m/', verbose_name='缩略图')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='专题内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '专题管理',
                'verbose_name_plural': '专题管理',
            },
        ),
    ]
